### ISSUE TITLE
JSONiq: Arrow doesn't work with inline functions

### ISSUE THREAD

**Issue by nerfpops** [RumbleDB/rumble#1021]
This doesn't work: `"test" => function ($str) { "ok" }`

Workaround:
```xquery
declare function f($arrow-val, $fn)
{
  $fn($arrow-val)
};

"test" => f(function($str) { "ok" })
```

**Comment by ghislainfourny** [comment]
Thanks a lot, indeed I think it is only implemented for static calls for now. We will look into it.

**Comment by ghislainfourny** [comment]
Happy to announce that this is now supported in the master, and it will be part of the next release!

**Comment by ghislainfourny** [comment]
As a comment regarding the query in the original comment: please note that the syntax is like this:

"test" => (function ($str) { "ok" })()

i.e., the dynamic function must actually be called.
