### ISSUE TITLE
Is there any CLI parameter to set AppName

### ISSUE THREAD

**Issue by mrceyhun** [RumbleDB/rumble#1023]
Dear @ghislainfourny and Rumble team,

I found that there is AppName[1] constant. Is there any cli parameter to change the default app name?

Best,
Ceyhun

[1] https://github.com/RumbleDB/rumble/blob/6ca34a9b123c6fc8066afb5a4cf3a0d5e0679699/src/main/java/sparksoniq/spark/SparkSessionManager.java#L54

**Comment by ghislainfourny** [comment]
Hi Ceyhun,

There is --conf spark.app.name=your_name

I wil check if Rumble overrides this. If it does, I will fix it so it doesn't.

Thanks and kind regards,
Ghislain

**Comment by ghislainfourny** [comment]
The fix is on the way.

**Comment by ghislainfourny** [comment]
@mrceyhun do you agree if we close this issue?

**Comment by mrceyhun** [comment]
Yes @ghislainfourny please close. Thanks a lot!
