### ISSUE TITLE
optimization issue of count after group by

### ISSUE THREAD

**Issue by wzrain** [RumbleDB/rumble#1150]
Issue:
These two queries:
`for $i in json-file("git-archive.json") 
let $k := $i.payload.commits[] 
group by $r := $i.repo.id 
order by count($k.author) descending 
count $c where $c <= 5 
return {"repo":$r, "count":count($k.author)}`
and 
`for $i in json-file("git-archive.json") 
let $k := $i.payload.commits[].author
group by $r := $i.repo.id 
order by count($k) descending 
count $c where $c <= 5 
return {"repo":$r, "count":count($k)}`
should have returned the same results but didn't.
(git-archive dataset: https://polybox.ethz.ch/index.php/s/tzpZtUnTXBPlFAO)

Possible reason:
In the second query, the `count` function with a bare variable as the parameter (`count($k)`) will be marked with `VariableDependency.COUNT`. When it acts as an aggregation function of a group by clause, it will be optimized here in order to avoid storing all the values bound to the variable: https://github.com/RumbleDB/rumble/blob/master/src/main/java/org/rumbledb/runtime/flwor/FlworDataFrameUtils.java#L677. However that particular implementation will only count the number of *dataframe rows* within each group rather than the number of actual *items*, which could be incorrect due to the fact that each row can represent a *sequence* of multiple items in cases like `let $k := $i.payload.commits[].author`. 

Suggestion:
It would be great if you could distinguish between the variable from the `for` clause (`$i` in the examples above) and those variables created with `let` clause during the flwor expression, because I reckon that optimization of only preserving the count result only works for the variable from the `for` clause.

**Comment by ghislainfourny** [comment]
Reproduced on a smaller dataset:

    for $i in parallelize((
        { "commits" : [ { "author" : "Einstein" } ]},
        { "commits" : [ { "author" : "Goedel" }, { "author" : "Ramanujan" } ]}
      ))
      let $k := $i.commits[].author
      group by $r := 1
      return {"repo":$r, "count":count($k)}

**Comment by wzrain** [comment]
This info log also needs to be changed: https://github.com/RumbleDB/rumble/blob/master/src/main/java/org/rumbledb/runtime/flwor/clauses/GroupByClauseSparkIterator.java#L576. It can be very misleading due to the incorrect clause name printed.

**Comment by ghislainfourny** [comment]
@wzrain many thanks for your insights. This is now fixed and will make it into the next release.

**Comment by wzrain** [comment]
@ghislainfourny Thanks for the quick response on the issue! Although now the query I mentioned in my original comment:
```
for $i in json-file("git-archive.json") 
let $k := $i.payload.commits[].author 
group by $r := $i.repo.id 
order by count($k) descending 
count $c where $c <= 5 
return {"repo":$r, "count":count($k)}
```
leads to a new error:
```
[ERROR] An error has occurred: cannot resolve '`k.sequence.sequence`' given input columns: [__auto_generated_subquery_name.grouping_columns, __auto_generated_subquery_name.i, __auto_generated_subquery_name.k.sequence, __auto_generated_subquery_name.r.sequence]; line 1 pos 23;
'Aggregate [grouping_columns#10], ['sum('cardinality('`k.sequence.sequence`)) AS k.sequence#11, first(r.sequence#6, false) AS r.sequence#13]
+- SubqueryAlias __auto_generated_subquery_name
   +- Project [i#1, k.sequence#3, r.sequence#6, createGroupingColumns(struct(r.sequence, r.sequence#6)) AS grouping_columns#10]
      +- SubqueryAlias input5d89821c16cc497a8b7a7789987b4434
         +- Project [i#1, k.sequence#3, letClauseUDF(struct(i, i#1)) AS r.sequence#6]
            +- SubqueryAlias inputc0a2110f1ad6434ea979e0156fec7463
               +- Project [i#1, letClauseUDF(struct(i, i#1)) AS k.sequence#3]
                  +- SubqueryAlias inputc5128f29cf45433eaae533dfa6d619e2
                     +- LogicalRDD [i#1], false

We should investigate this 🙈. Please contact us or file an issue on GitHub with your query. 

```
Looks like it's due to your latest fix.

**Comment by wzrain** [comment]
> @ghislainfourny Thanks for the quick response on the issue! Although now the query I mentioned in my original comment:
> 
> ```
> for $i in json-file("git-archive.json") 
> let $k := $i.payload.commits[].author 
> group by $r := $i.repo.id 
> order by count($k) descending 
> count $c where $c <= 5 
> return {"repo":$r, "count":count($k)}
> ```
> 
> leads to a new error when tested on the latest master branch:
> 
> ```
> [ERROR] An error has occurred: cannot resolve '`k.sequence.sequence`' given input columns: [__auto_generated_subquery_name.grouping_columns, __auto_generated_subquery_name.i, __auto_generated_subquery_name.k.sequence, __auto_generated_subquery_name.r.sequence]; line 1 pos 23;
> 'Aggregate [grouping_columns#10], ['sum('cardinality('`k.sequence.sequence`)) AS k.sequence#11, first(r.sequence#6, false) AS r.sequence#13]
> +- SubqueryAlias __auto_generated_subquery_name
>    +- Project [i#1, k.sequence#3, r.sequence#6, createGroupingColumns(struct(r.sequence, r.sequence#6)) AS grouping_columns#10]
>       +- SubqueryAlias input5d89821c16cc497a8b7a7789987b4434
>          +- Project [i#1, k.sequence#3, letClauseUDF(struct(i, i#1)) AS r.sequence#6]
>             +- SubqueryAlias inputc0a2110f1ad6434ea979e0156fec7463
>                +- Project [i#1, letClauseUDF(struct(i, i#1)) AS k.sequence#3]
>                   +- SubqueryAlias inputc5128f29cf45433eaae533dfa6d619e2
>                      +- LogicalRDD [i#1], false
> 
> We should investigate this 🙈. Please contact us or file an issue on GitHub with your query. 
> ```

Reproducible with the smaller dataset:
```
for $i in parallelize((
    { "commits" : [ { "author" : "Einstein" } ], "repo":"r2"},
    { "commits" : [ { "author" : "Goedel" }, { "author" : "Ramanujan" } ], "repo": "r1"}
))
let $k := $i.commits[].author
group by $r := $i.repo
return {"repo":$r, "count":count($k)}
```

**Comment by ghislainfourny** [comment]
Fixed in #1159

**Comment by wzrain** [comment]
@ghislainfourny Thanks for the follow-up. Although I don't really agree that the queries produce the expected result. For the query on the smaller dataset mentioned above:
```
for $i in parallelize((
    { "commits" : [ { "author" : "Einstein" } ], "repo":"r2"},
    { "commits" : [ { "author" : "Goedel" }, { "author" : "Ramanujan" } ], "repo": "r1"}
))
let $k := $i.commits[].author
group by $r := $i.repo
return {"repo":$r, "count":count($k)}
```
I think it should return
```
{ "repo" : "r1", "count" : 2 }
{ "repo" : "r2", "count" : 1 }
```
instead it returns
```
{ "repo" : "r1", "count" : 1 }
{ "repo" : "r2", "count" : 1 }
```

**Comment by ghislainfourny** [comment]
You are right. I will reiterate.

**Comment by wzrain** [comment]
> You are right. I will reiterate. I think I know where the issue is: since $k is recognized as a count-only, the column for $k is incorrectly initialized with constant 1s but it should be initialized with the pre-group $k count.

Exactly. This is actually what this issue is initially about. :)

**Comment by ghislainfourny** [comment]
The fix is on the way.

#1162 

In fact it was something different: the counts were correctly computed, but not marked as counts, so they were treated as items and "the counts were counted again" (to 1).

**Comment by wzrain** [comment]
@ghislainfourny Thanks for the fix! The `CountFix` branch looks good to me now.

**Comment by ghislainfourny** [comment]
@wzrain does it now work? :)

**Comment by wzrain** [comment]
@ghislainfourny Thanks for the fix! It works now. Issue closed. :)
