### ISSUE TITLE
position() and last()

### ISSUE THREAD

**Issue by ghislainfourny** [RumbleDB/rumble#120]
In filters, position() and last() are not supported yet.

**Comment by CliffordAnderson** [comment]
@ghislainfourny We ran into the lack of those functions today. It would be great to add them to the language. Just a 👍.

**Comment by ghislainfourny** [comment]
Many thanks @CliffordAnderson for your feedback! :)

**Comment by ghislainfourny** [comment]
.. and done :)

**Comment by CliffordAnderson** [comment]
@ghislainfourny Thank you so much! I really appreciate your implementing these features so quickly. Can't wait to try them out.

**Comment by ghislainfourny** [comment]
@CliffordAnderson this will be in the next release, but I would be happy to prepare a jar with the current master for you, if you would like to already try this now.

**Comment by ghislainfourny** [comment]
@CliffordAnderson many thanks for your kind words!
