### ISSUE TITLE
TODOs DataFrames

### ISSUE THREAD

**Issue by ghislainfourny** [RumbleDB/rumble#203]
1. Map List<> to DataFrame arrays and serialize Items (rather than serialize List<Item>)
2. Migrate to spark SQL
3. Do not include class information in kryo binary
4. Pooling of Input and Output

**Comment by CanBerker** [comment]
Can this be closed?

**Comment by ghislainfourny** [comment]
Yes, and it feels good to see all the progress made, doesn't it? :)

**Comment by CanBerker** [comment]
Definitely :)
