### ISSUE TITLE
Optimize Dataframe Kryo Instance Management

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#234]
Looking at a profiler, it seems that a considerable part of the time is also spent getting and releasing the kryo object. However, it seems that only a kryo instance per core is actually created locally (which is optimal), so I am not sure where this overhead comes from. Maybe something to investigate later on.

_Originally posted by @ghislainfourny in https://github.com/Sparksoniq/sparksoniq/pull/225_

**Comment by ghislainfourny** [comment]
Fixed.
