### ISSUE TITLE
Variable values not passed to parallel execution

### ISSUE THREAD

**Issue by ghislainfourny** [RumbleDB/rumble#244]
for $rank in 1 to 4
return {
  "Rank" : $rank,
  "Count" : count(
    for $i in json-file("/tmp/input.json", 100)
    where $i.target eq $i.choices[[$rank]]
    return 1
  )
}

Error [err: XPDY0130 ] Runtime error retrieving variable $rank value

Another case:

let $guess := (for $i in json-file("confusion-2014-03-02/confusion-2014-03-02.json", 10)
							order by $i.guess
							count $c
							where $c<=1
							return $i.guess)

return count(for $i in json-file("confusion-2014-03-02/confusion-2014-03-02.json", 10)
							where $i.target = $guess
							return 1)

**Comment by CanBerker** [comment]
The last query fails with a parser exception:

Error [err: XPST0003]LINE:4:COLUMN:0:Parser failed. 

return count(for $i in json-file("./src/main/resources/queries/conf-ex.json", 10)
where $i.target = $guess
return 1)

**Comment by ghislainfourny** [comment]
> The last query fails with a parser exception:
> 
> Error [err: XPST0003]LINE:4:COLUMN:0:Parser failed.
> 
> return count(for $i in json-file("./src/main/resources/queries/conf-ex.json", 10)
> where $i.target = $guess
> return 1)

This is the second part of the upper query -- the query is

let $guess := (for $i in json-file("confusion-2014-03-02/confusion-2014-03-02.json", 10)
order by $i.guess
count $c
where $c<=1
return $i.guess)
return count(for $i in json-file("confusion-2014-03-02/confusion-2014-03-02.json", 10)
where $i.target = $guess
return 1)

**Comment by CanBerker** [comment]
Thanks for the clarification
