### ISSUE TITLE
publish rumbledb jars to maven central

### ISSUE THREAD

**Issue by pjfanning** [RumbleDB/rumble#305]
Would it be possible to publish rumble jars to MavenCentral (via Sonatype, for instance)?

https://repo1.maven.org/maven2/org/rumbeldb is not found

spark-rumble-1.1.jar is a 'fat jar', ie it has the classes from multiple external dependencies (eg antlr, commons-lang3, etc) - Ideally, a jar published to maven central would only have the rumble classes and have the dependencies in the pom.xml.

**Comment by ghislainfourny** [comment]
Many thanks for the hint, we will consider this.

Indeed the jar is fat -- it assumes an environment with the Spark library, so that only Spark+Spark SQL are not included in the jar, everything else is.

**Comment by ghislainfourny** [comment]
This is now done. I am closing this issue.
