### ISSUE TITLE
String functions

### ISSUE THREAD

**Issue by ghislainfourny** [RumbleDB/rumble#34]
Functions left to implement:

codepoints-to-string#1, string-to-codepoints#1, compare#2, compare#3, codepoint-equal#2, string-length#0, string-length#1, normalize-space#0, normalize-space#1, normalize-unicode#1, normalize-unicode#2, upper-case#1, lower-case#1, translate#3, contains#2, substring-before#2, substring-before#3, substring-after#2, substring-after#3

Later (needs collations):
ends-with#3
contains#3
starts-with#3

**Comment by ghislainfourny** [comment]
@CodingKaiser are there any functions from that list that still remain? If so, could we list them for future reference? Thanks!

**Comment by ghislainfourny** [comment]
@pierremotard Do you think we can now close this issue, or is there any uncovered function?

**Comment by mschoeb** [comment]
compare is now implemented and I double checked: every string function is now implemented
so I will close this for now
