### ISSUE TITLE
Enable User Defined (Static/Dynamic) Function invocation with RDDs/DFs

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#342]
Kryo serialization doesn't support the Expression class found in FunctionItem which is used for function invocations. Kryo needs to be extended to support user defined function invocations on spark

**Comment by CanBerker** [comment]
@ghislainfourny The FunctionItem which gets serialized by Kryo to be passed into the RDD stores 'Expression' (Storing expressions is necessary as they enable recursive functions). Should Kryo be extended which all the Expression Types & Types they reference inside their implementations to work?

This would mean quite a bit of classes to add to Kryo. This worried me whether it would impact Kryo performance as well as I would be quite a change to rollback. Could you provide your opinion on fixing this issue

**Comment by ghislainfourny** [comment]
@CanBerker this is a very good question.

In the short term, I suggest "squeezing" the Java IO serialization of the function iterator inside Kryo, that is, inside the write function of Kryo in the function item, calling the Java IO serializer on the iterator, and writing back that sequence of bytes "as is" to Kryo.

This should be straightforward to do.

This should do the trick as a first approach for passing functions that don't have a closure, buying us some time to think about Kryo later and experiment.

Does it help?

**Comment by CanBerker** [comment]
The idea definitely makes sense. I felt the need to point out one thing though: functionItem stores a field with the type of Expression (Base Expression class, where all other expressions inherit from) rather than a RuntimeIterator for the body (this is the part that enables recursion). I am currently working on getting expressions and related custom classes to play nicely with Kryo.

I have also ran into the following excerpt in the section given below: Having many default serializers doesn't affect serialization performance, so by default Kryo has 50+ default serializers for various JRE classes. Additional default serializers can be added:
https://github.com/EsotericSoftware/kryo#default-serializers
I believe this may be applying to our case but I'm not 100% sure if default serializer count doesn't affect performance also means registered class count doesn't affect performance. This probably needs further investigation.
