### ISSUE TITLE
Tests failing on travis but passing locally

### ISSUE THREAD

**Issue by AndreaRinaldi1** [RumbleDB/rumble#349]
I am having issues with travis, as some tests where dayTimeDuration is multiplied (or divided) by a decimal are failing, but locally everything looks fine. I also tried on another machine, and there looks fine as well. 

For example, when running `7.321 * dayTimeDuration("P12DT2H81M2.001S")`, it should yield `P88DT20H58M38.709S` but results in `PT20H58M38.709S` on travis. The issue is the same for all the other similar tests, i.e. the day field is not included in the resulting duration.

**Comment by ghislainfourny** [comment]
@wscsprint3r would you have a chance to take a look? Maybe some version issue with the libraries, Java or the OS?

**Comment by ghislainfourny** [comment]
On my machine, all tests work fine with this branch.
