### ISSUE TITLE
Use tests rather than exceptions while switching between builtin/UDF functions

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#362]
Can you make a note/issue for the future to use a test rather than use exceptions to switch between builtin/UDF? It makes a difference in performance. Exceptions should only be used for actual errors.

It's good for now (correctness and design of test cases had priority) but we should keep it in mind.

We could talk about this next week to clean up the mechanism.

_Originally posted by @ghislainfourny in https://github.com/RumbleDB/rumble/pull/350_

**Comment by ghislainfourny** [comment]
@CanBerker Is this actually now fixed?

**Comment by CanBerker** [comment]
Yes I had addressed this some time ago. We can close the issue

**Comment by ghislainfourny** [comment]
Thanks!
