### ISSUE TITLE
Undeterministic failure of count clause

### ISSUE THREAD

**Issue by ghislainfourny** [RumbleDB/rumble#404]
Sometimes, using the count clause fails with a null pointer exception because some partition IDs do not get assigned a partition offset in the underlying Spark SQL algorithm.

Reproduceable (not always) with:

for $i in json-file("confusion-2014-03-02/confusion-2014-03-02.json", 10)
    order by $i.date descending
    count $c
    where $c <= 1
    return $i.date

**Comment by CanBerker** [comment]
Solved in #406
