### ISSUE TITLE
ForClauseVariables and LetClauseVariables should not be treated as individiual clauses

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#443]
This may need disentanglement later -- there might be several variables in the same clause, but that is still the same clause.

In the current implementation, these are treated as several clauses. In the long-term we will need to address this (you can simply raise an issue).

_Originally posted by @ghislainfourny in https://github.com/RumbleDB/rumble/pull/432_

**Comment by ghislainfourny** [comment]
After checking the W3C specification does say that several variables are equivalent to several separate clauses. We are thus now correct in our execution of queries with multiple variables in a clause. Do you agree?

**Comment by CanBerker** [comment]
Sounds great!
