### ISSUE TITLE
Implement a materializeSingleton method for RuntimeIterator baseclass

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#444]
Could we check that 

switch((1, 2)) case 1 return 0 default return 2

returns an error?

In other words, do we check there are no extra items?

In a nutshell, we might need to have two rather than one methods depending on whether we check or not:

materializeOneItemOrNull (checks that there is no second one, i.e., hasNext = false after that)

materializeFirstItemOrNull (does NOT check that there is no second one, if we don't care)

_Originally posted by @ghislainfourny in https://github.com/RumbleDB/rumble/pull/439_

**Comment by ghislainfourny** [comment]
That's also done, with clean exceptions for the first version.
