### ISSUE TITLE
Materialization of RuntimeIterators: Implement materialize singleton

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#499]
As far as I know we have two materialize methods: one that materializes everything and another one that materializes the first result if it exists (otherwise returns null). The 'materialize singleton' as I call it has not been implemented yet. That is, materializes a singleton result and throws an error result set is not a singleton(either empty or multiple). Once implemented this can be used in multiple places across the project.

_Originally posted by @CanBerker in https://github.com/RumbleDB/rumble/pull/471_

**Comment by ghislainfourny** [comment]
This is done.
