### ISSUE TITLE
DF-Enabled TypePromotionIterator

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#500]
TypePromotionIterator needs to be extended with DF execution.

In the current state, typePromotionIterator wraps every parameter and return value for a function that does not expect item*. Since typePromotionIterator is only RDD-enabled, all variables that go through this iterator is stored as an RDD in the dynamic context. 

This is very limiting while working with especially transformers and estimators. These functions expect dataframes as input and since typePromotionIterator wrapping VariableReferences downgrade everything to RDD, this makes it impossible to reference dataframes as variables. The current workaround is simply changing signature of parameters and return types to item* so that typePromotion won't be applied. 

Once typePromotionIterator has a DataFrame execution mode enabled. These workaround can be removed, enabling estimator and transformers to have their correct signatures.

**Comment by ghislainfourny** [comment]
This should now be fixed. Both TreatAs and TypePromotion support DF for + and * (and cleanly materialize for ? and 1).
