### ISSUE TITLE
Invalid file input causes a false OurBadException

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#593]
spark-submit --master local[*] --conf "spark.driver.host"="127.0.0.1" rumbleml/spark-rumble-1.4-jar-with-dependencies.jar --query-path ./does-not-exist.json

> An error has occured: ./does-not-exist.json 
> We should investigate this 🙈. Please contact us or file an issue on GitHub with your query.
> Link: https://github.com/RumbleDB/rumble/issues

**Comment by ghislainfourny** [comment]
@CanBerker does it still happen with the latest master! Thanks!

**Comment by CanBerker** [comment]
```
noglob spark-submit --master local[*] --conf "spark.driver.host"="127.0.0.1" target/spark-rumble-1.5.1-jar-with-dependencies.jar --query-path ./does-not-exist.json
Listening for transport dt_socket at address: 5005
20/04/07 21:49:16 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
⚠️  ️Error [err: FODC0002]LINE:0:COLUMN:0:Query file does not exist.
```

Looks good now. Well done
