### ISSUE TITLE
Rumble output should not be truncated when executed on files

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#596]
Example Query:
 ```
spark-submit --master local[*] --conf "spark.driver.host"="127.0.0.1" rumbleml/spark-rumble-1.4-jar-with-dependencies.jar --query-path ./rumbleml/rumbleml-kmeans-libsvm.jq --output-path ./results/rumbleml-kmeans-libsvm-result.json --log-path ./results/rumbleml-kmeans-libsvm-log.txt
```
The following truncation should not happen
>Results have been truncated to:200 items. This value can be configured with the --result-size parameter at startup

**Comment by ghislainfourny** [comment]
@CanBerker could you share your query, and tell me if it still happens with the latest version of the master? Thanks!

**Comment by CanBerker** [comment]
Unfortunately it still occurs. My example queries are given below but it should happen with any query:
```
let $data := libsvm-file("./data/covtype-2500.scale")
let $estimator := get-estimator("KMeans")
let $transformer := $estimator(
    $data,
    {"k": 2, "seed": 1}
)
let $result := $transformer(
    $data,
    { }
)
return $result
```

```
let $data := (
    let $rdd := json-file("./data/IMDB_reviews-2500.json")
    for $entry in $rdd
    let $edited := {
        "movie_id": $entry.movie_id,
        "user_id": $entry.user_id,
        "is_spoiler": $entry.is_spoiler,
        "rating": $entry.rating cast as integer
    }
    return $edited
)

let $df := annotate(
    $data,
    {
        "movie_id": "string",
        "user_id": "string",
        "is_spoiler": "boolean",
        "rating": "decimal"
    }
)

let $estimator := get-estimator("KMeans")
let $transformer := $estimator(
    $df,
    {"featuresCol": ["rating"], "k": 3, "seed": 1}
)

let $result := $transformer(
    $df,
    {"featuresCol": ["rating"]}
)
return $result

```

**Comment by ghislainfourny** [comment]
@CanBerker I see, it's because of the let's. This is a known issue: #615

**Comment by CanBerker** [comment]
I see, feel free to close this issue then

**Comment by ghislainfourny** [comment]
Fixed in PR #627

**Comment by ghislainfourny** [comment]
@CanBerker is it now fixed in the latest master?

**Comment by CanBerker** [comment]
Here is the current behavior:
Query:
```
let $data := libsvm-file("./data/covtype-100k.scale")
let $estimator := get-estimator("KMeans")
let $transformer := $estimator(
    $data,
    {"k": 2, "seed": 1}
)
let $result := $transformer(
    $data,
    { }
)
return null
```

Command:
`
spark-submit --master local[*] --conf "spark.driver.host"="127.0.0.1" rumbleml/spark-rumble-1.5.1-jar-with-dependencies.jar --query-path ./rumbleml/rumbleml-kmeans-libsvm-100k.jq --output-path ./results/test-result.json --log-path ./results/test-log.txt
`

Result:
`  ️Error [err: RBDY0005]LINE:7:COLUMN:15:Cannot materialize a sequence of 100000 items because the limit is set to 200. This value can be configured with the --result-size parameter at startup`

**Comment by ghislainfourny** [comment]
Now it's only a warning.
