### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by ghislainfourny** [RumbleDB/rumble#6]
Support library modules

**Comment by DanGraur** [comment]
I would tend to agree that the addition of modules could prove to have a strong positive impact in the long run. I'm currently writing up the [CERN ADL Benchmarks](https://github.com/iris-hep/adl-benchmarks-index) in JSONiq over Rumble+Spark, and I often have to copy-paste function code from one query script to another. This makes the query scripts more cluttered, and, in turn, it gives the initial false impression that the queries are more complex than they really are. Moreover, if one function (on which multiple queries depend) changes, then one needs to manually go through all the query scripts and apply the same change repeatedly. This implies greater programmer effort, and can even lead to higher chances of coding errors.

**Comment by ghislainfourny** [comment]
@DanGraur this is done and will be officially released in the coming days. Thanks for your feedback!
