### ISSUE TITLE
Persist history

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#613]
It would be great to persist the history of the shell between invocations. The library you are using (?) hopefully has a configuration option for that.

**Comment by ingomueller-net** [comment]
It seems like this can be activated with a single line of code (see [example usage] (https://github.com/trinodb/trino/blob/fe608f2723842037ff620d612a706900e79c52c8/client/trino-cli/src/main/java/io/trino/cli/InputReader.java#L46)).

**Comment by mschoeb** [comment]
Great idea, this is now implemented in the newest branch on gitlab 👍
