### ISSUE TITLE
Cleanup invalid function signatures on error

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#631]
Invalid function call fails as expected:
```
rumble$ declare function add_two_static($i) {
    $i+2
};
add_two_static()
```
`⚠️  ️Error [err: XPST0017]LINE:4:COLUMN:0:Undefined function call; Entered function name and arity doesn't match a defined function signature: "add_two_static" called with 0 parameters.`

The bug is : "The execution mode is added to the catalog but the function body is not".
Calling the function causes errors b/c function is not properly defined (no implementation):
```
rumble$ add_two_static(2)
```
`⚠️  ️Error [err: XPST0017]LINE:1:COLUMN:0:Undefined function call; Entered function name and arity doesn't match a defined function signature: "add_two_static" called with 1 parameters.`

Yet, function cannot be declared as its signature persists from the failed run and redeclaration is not permitted (query simply returns 1 as an arbitrary value to succeed): 
```
rumble$ declare function add_two_static($i) {
    $i+2
};

1
```
`⚠️  ️Error [err: XQST0034]LINE:1:COLUMN:0:Function already exists; "add_two_static" with arity: 1`

**Comment by ghislainfourny** [comment]
The support in the shell for remembering previous functions/variables is indeed buggy and will need to be designed cleanly. There should also be a meta-way to undeclare or redeclare functions/variables that is specific to the shell.

**Comment by ghislainfourny** [comment]
Update: now function declarations are cleaned every time to avoid the issue.

In the future, we might consider "caching" previous functions, but this will need a clean design.
