### ISSUE TITLE
Addition of `trace` routine 

### ISSUE THREAD

**Issue by DanGraur** [RumbleDB/rumble#679]
The addition of a `trace` routine, which essentially acts as a `print` method, would be very helpful towards developing and debugging queries. 

Currently, observing the state of a query execution at a particular moment in time is not straight-forward. This requires, more or less, carefully removing or commenting out certain chunks of the query, such that one returns the state to be observed as the result of the query. While this does not entail a considerable effort for small queries, for big queries (which is precisely the place where these debugging tools become most useful) the effort begins to show. Such a tool could prove invaluable in the long run.

**Comment by ghislainfourny** [comment]
Thanks, Dan! This is in progress #695

**Comment by ghislainfourny** [comment]
This will be released in the coming days.
