### ISSUE TITLE
Bang Operator (Map Operator) Implementation

### ISSUE THREAD

**Issue by CanBerker** [RumbleDB/rumble#72]
let $o := {"foobar": 2, "1" : "bar"}
return ("foo", "bar", "foobar") ! ($o.$$)
_returns 2_

the bang operator (I believe it's also called MapOperator http://www.jsoniq.org/docs/JSONiq/html-single/index.html#idm16200896), the expression definition and related mechanisms seem to be not implemented. (I think the same case also applies to the CountClause which is right above in the documentation.

Previously encountered in PR https://github.com/Sparksoniq/sparksoniq/pull/59

**Comment by ghislainfourny** [comment]
Note: this should also be pushed down to Spark if the left-hand side has an RDD.

**Comment by ghislainfourny** [comment]
@CodingKaiser this is what you are working on now, so I am assigning this issue to you.

**Comment by CodingKaiser** [comment]
Yes, I am working on this at the moment. A local version has been implemented, with the Hybriditerator-based implementation to follow.

**Comment by ghislainfourny** [comment]
This is done.
