### ISSUE TITLE
"An error has occured: Index: 0, Size: 0" when run through web server

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#729]
The following query produces an error when run through the HTTP interface:

```xquery
for $x in json-file("bla.json") (: bla.json only contains {} :)
let $foo := $x.foo
return count($foo)
```

The error (through HTTP) I get is the following:

```
RuntimeError: An error has occured: Index: 0, Size: 0 We should investigate this 🙈. Please contact us or file an issue on GitHub with your query. Link: https://github.com/RumbleDB/rumble/issues
```

Interestingly, the same query/file combination works when run through the CLI.

**Update:** I only tested with v1.7.0.

**Comment by ghislainfourny** [comment]
Also fixed!

**Comment by ghislainfourny** [comment]
It actually also did not work on the CLI and nowhere else. It was an issue with the count() interfering with the group-by optimization of aggregations.

**Comment by ingomueller-net** [comment]
Great, works for me as well! Thanks :)
