### ISSUE TITLE
Push aggregations into DataFrames

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#765]
The following should work even when Rumble is run with `--result-size 3`:

```xquery
sum(parallelize(1 to 4))
```

Currently, it fails with `Cannot materialize a sequence of 4 items because the limit is set to 3.` Instead, the `sum` function and other aggregations should be pushed into the DataFrame API, where they can be computed in parallel on the cluster.

**Comment by mschoeb** [comment]
All aggregations (min, max, count, sum, avg) have since been pushed down into dataframes so I will close this for now
