### ISSUE TITLE
Quantified expression no extraction of effective boolean value

### ISSUE THREAD

**Issue by mario-arduini** [RumbleDB/rumble#801]
in quantified expressions, queries like

some $a in (1,2,"a") satisfies $a 
throws An error has occurred: org.rumbledb.items.IntItem cannot be cast to org.rumbledb.items.BooleanItem

it seems they cannot produce the effective boolean value of the test condition

**Comment by ghislainfourny** [comment]
Suggestion: convert quantified expression to FLWOR runtime iterators to make it future proof and avoid writing the same code twice

some $a in (1,2,"a") satisfies $a

becomes

exists(for $a in (1, 2, "a") where $a return 0)

and

every $a in (1,2,"a") satisfies $a

empty(for $a in (1, 2, "a") where not $a return 0)

**Comment by mschoeb** [comment]
The suggested conversions have been implemented on main in the meantime
