### ISSUE TITLE
Type assertion fail

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#806]
Running following queries in Rumble return wrong answer:
```
abs(decimal("-0")) instance of decimal
abs(integer("-0")) instance of integer
```

The reason behind is that result is always returned as double for some reason

**Comment by ghislainfourny** [comment]
Many thanks, Stevan.

For future reference, I am including a link to the spec justifying that the above queries should return true:

https://www.w3.org/TR/xpath-functions-30/#func-abs

**Comment by mschoeb** [comment]
both cases (and double,float too) have since been fixed on master
