### ISSUE TITLE
switch comparison error

### ISSUE THREAD

**Issue by mario-arduini** [RumbleDB/rumble#821]
It seems that the switch expression is not able to compare different types when comparing the test expression with the different cases, according to the spec it should use deep-equal which allows for different types' comparison.
e.g.
switch(3)
case "a" return "a"
default return "b"
returns RBST0004 : Comparing an int to something that is not a number.

**Comment by ghislainfourny** [comment]
@mario-arduini could you confirm that this issue is fixed? Thanks!
