### ISSUE TITLE
Not able to compare durations using inequality

### ISSUE THREAD

**Issue by mario-arduini** [RumbleDB/rumble#822]
It is not possible to compare 2 yearMonthDurations or 2 dayTimeDurations using inequality operators like gt, le, <, etc...
It is not possible to compare yearMonthDuration and dayTimeDuration using equality operators like eq, etc...
Even if it is allowed in the spec (appendix B.2 operator mapping)

e.g (given these line of prolog)
declare variable $dtdur := "P2DT3H" cast as dayTimeDuration;
declare variable $ymdur := "P1Y2M" cast as yearMonthDuration;

$dtdur le $dtdur

$ymdur > $ymdur

$dtdur eq $ymdur

all return XPTY0004 : "dayTimeDuration": invalid type: can not compare for equality to type "dayTimeDuration"
(types to be changed according to the example we are examining)

**Comment by ghislainfourny** [comment]
@mario-arduini could you confirm that this issue is fixed? Thanks!
