### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#829]
In version 1.8, when dividing by +0e0 you were getting FOAR0001 error, while dividing with -0e0 you were getting -Infinity.
Starting from version 1.9, division with -0e0 started yielding the same error. 
In both cases, this is wrong, according to test suite the correct and expected output is the Infinity and not the Error code
In case that number you want to divide is also 0, the expected output will be NaN and not the Error code

In case that you are dividing by 0, +0.0, -0.0, only then the expected output is FOAR0001 error.

See image below:
![image](https://user-images.githubusercontent.com/74027761/101027176-11728e80-3578-11eb-8a72-f1be6d97dad2.png)

Test cases for verification:
Check in numeric-divide test cases range from K2-NumericDivide-1 to K2-NumericDivide-16

Additional tests:
<test>3 mod xs:double("-0")</test>
         <assert-string-value>NaN</assert-string-value>
<test>xs:double("-0") mod xs:double("-0")</test>
         <assert-string-value>NaN</assert-string-value>
[numeric-divide.log](https://github.com/RumbleDB/rumble/files/5636682/numeric-divide.log)

**Comment by ghislainfourny** [comment]
@mstevan this is all fixed. Thank you for reporting!

**Comment by mstevan** [comment]
I can confirm that this is fixed. Furthermore hard-coded conversion of INF to Infinity is not required anymore as the output is according to the expected result! 

The single thing remaining is to investigate what happens when having spaces in ctor double(" INF ") as it should return INF
