### ISSUE TITLE
Converting string to number issue

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#830]
YeX becomes a string with many X 0's instead of YeX. Sample below will result in assertion of 100000000 eq 1.0E8 which fails!
Test: xs:double("1e8") cast as xs:string</test>
Expected result: 1.0E8

**Comment by ghislainfourny** [comment]
This is fixed

**Comment by mstevan** [comment]
All tests are passing. At the moment, there are no other tests crashing because of fix
