### ISSUE TITLE
SQL error: mismatched input

### ISSUE THREAD

**Issue by jscissr** [RumbleDB/rumble#836]
It looks like I found a bug in rumble while solving the exercises from the Big Data lecture.
This is using rumble 1.9.1.

Query:
```
count(for $i in json-file("/tmp/confusion-2014-03-02/confusion-2014-03-02.json", 10)
group by $target := $i.target
return true)
```

Result:

```
An error has occured: 
mismatched input '`i`' expecting ')'(line 1, pos 21)

== SQL ==
select  from (select `i`,`target`, createGroupingColumns(struct(`target`)) as `grouping_columns` from input) group by `grouping_columns`
---------------------^^^
 We should investigate this 🙈. Please contact us or file an issue on GitHub with your query. Link: https://github.com/RumbleDB/rumble/issues
```

The json file can be downloaded at http://data.greatlanguagegame.com.s3.amazonaws.com/confusion-2014-03-02.tbz2 but is probably irrelevant.

**Comment by ghislainfourny** [comment]
Very nice catch, @jscissr, many thanks. Indeed this probably happens because the return clause is a constant. We will investigate.

**Comment by ghislainfourny** [comment]
@jscissr happy to report that this is fixed. I prepared a new jar with the current master [here](https://polybox.ethz.ch/index.php/s/N7lx0eP7KWsbiNi).

Also, a quick hint: this query is simpler and does the same thing (distinct-values is also pushed down to a distinct transformation in Spark):

    count(distinct-values(json-file("/Users/Ghislain/Code/datasets/confusion-2014-03-02/confusion-2014-03-02.json", 10).target))

**Comment by jscissr** [comment]
That was very quick. Thanks!
