### ISSUE TITLE
max and min function not performing auto conversion

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#861]
@mstevan
test-set: max.xml, min.xml
test-cases: fn-max-16 and fn-min-16

@team
Seems that min and max function do not auto convert to string when possible

**Input:**
min((anyURI("http://a.com"), "http://b.com"))

**Output:**
⚠️  ️There was an error.

Code: [FORG0006] (this code can be looked up in the documentation and specifications).

Location information: file:/Users/mstevan/Documents/:LINE:1:COLUMN:0:

Min expression input error. Input has to be non-null atomics of matching types: There was an error.

Code: [RBST0004] (this code can be looked up in the documentation and specifications).

Location information: none:LINE:0:COLUMN:0:

http://b.com http://a.com

**Expected output:**
<all-of>
  <assert-eq>"http://a.com"</assert-eq>
  <assert-type>xs:string</assert-type>
</all-of>

**Comment by ghislainfourny** [comment]
This is fixed.
