### ISSUE TITLE
round() throws an error for infinite values

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#865]
@mstevan
test-set: round.xml; round-half-to-even.xml
test-cases: K2-RoundFunc-13, 14, 22; K2-RoundEvenFunc-11, 13, 15

@team
I cannot instantiate a double that is INF or NaN. It throws java.lang.NumberFormatException: Infinite or NaN
In console I get this error message. Same problem is for NaN

**Input:**
round(double("INF"))

**Output:**
⚠️  ️There was an error.

Code: [XPTY0004] (this code can be looked up in the documentation and specifications).

Location information: file:/Users/mstevan/Documents/:LINE:1:COLUMN:6:

INF: value of type string is not castable to type double.

**Expected output:**
INF

**Comment by ghislainfourny** [comment]
This should already have been fixed in the master, which I pushed again to GitLab. It is even released.

**Comment by ghislainfourny** [comment]
However, round(double("INF")) doesn't seem to work, so there is still a bug with infinite values there.

**Comment by ghislainfourny** [comment]
This is now fixed.

**Comment by mstevan** [comment]
It is only working for round(). The same implementation should be used for round-half-to-even() function as well!
