### ISSUE TITLE
string-length weird behavior

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#867]
@mstevan
test-set: string-length.xml
test-cases: fn-string-length-24

@team
Weird behavior, please investigate

**Input:**
(1 to 100)[string-length() = 3]

**Output:**
⚠️  ️There was an error.

Code: [XPST0017] (this code can be looked up in the documentation and specifications).

Location information: file:/Users/mstevan/Documents/:LINE:1:COLUMN:11:

Undefined function call; Entered function name and arity doesn't match a defined function signature: "string-length" called with 0 parameters.

**Expected output:**
100

**Comment by ghislainfourny** [comment]
We don't support yet string-length#0, this is a missing feature.

**Comment by ghislainfourny** [comment]
This is now fixed!
