### ISSUE TITLE
sum does not work if multiple arguments are of type dayTimeDuration

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#868]
@mstevan
test-set: sum.xml
test-cases: fn-sum-1,3,4,6, K-SeqSUMFunc-30,31

@team
Seems that sum does not work if multiple arguments are of type dayTimeDuration. It is fine if one is dayTimeDuration like in this example sum((), dayTimeDuration("PT0S")) will return PT0S

**Input:**
sum((dayTimeDuration("P1D"), dayTimeDuration("PT1H"))) instance of dayTimeDuration

**Output:**
⚠️  ️There was an error.

Code: [FORG0006] (this code can be looked up in the documentation and specifications).

Location information: file:/Users/mstevan/Documents/:LINE:1:COLUMN:0:

Sum expression has non numeric args P1D

**Expected output:**
true

**Comment by ghislainfourny** [comment]
This is fixed.

**Comment by mstevan** [comment]
All tests are passing. At the moment, there are no other tests crashing because of fix
