### ISSUE TITLE
sum does not work if we have NaN or INF

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#869]
@mstevan
test-set: sum.xml
test-cases: K-SeqSUMFunc-12, 13, 15

@team
Seems that sum does not work if we have NaN or INF in it as it tries to cast to decimal but fails

**Input:**
string(sum((1, 2, 3, double("NaN")))) eq "NaN"

**Output:**
⚠️  ️There was an error.

Code: [RBST0004] (this code can be looked up in the documentation and specifications).

Location information: file:/Users/mstevan/Documents/:LINE:1:COLUMN:7:

Cannot call castToDecimal on non numeric

**Expected output:**
true

**Comment by ghislainfourny** [comment]
This is fixed!

**Comment by mstevan** [comment]
All tests are passing. At the moment, there are no other tests crashing because of fix
