### ISSUE TITLE
Head works weird on arrays

### ISSUE THREAD

**Issue by mstevan** [RumbleDB/rumble#872]
@mstevan
test-set: array/head.xml 
test-cases: everything but more specific array-head-603

@team
It seems that head on array, does what head on sequence would do and looks at array as sequence of one element. But still the output is quite weird and not according to array:head in xml expectations

**Input:**
head([("a", "b"), ("c", "d")])

**Output:**
[ "a", "b", "c", "d" ]

**Expected output:**
"a", "b"

**Comment by ghislainfourny** [comment]
Again that's fn:head. We don't support array:head yet.

**Comment by mstevan** [comment]
For now we will exclude this test-set until feature is implemented (Category 2: Fails, as expected since it is not supported yet)
