### ISSUE TITLE
"Warning! Some execution modes could not be set."

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#921]
I always get the following (running from the docker image of version 1.10.0):

```Warning! Some execution modes could not be set. The query may still work, but we would welcome a bug report.```

What exactly should I report?

**Comment by ghislainfourny** [comment]
Hi Ingo.

The query :) Just to make sure it's not something we missed.

**Comment by ingomueller-net** [comment]
I just managed to produce a minimal example. Interestingly, this only happens with a DAG of included modules.

`a.jq`:
```xquery
module namespace a = "a.jq";
import module namespace b = "b.jq";
```

`b.jq`:
```xquery
module namespace b = "b.jq";
import module namespace c = "c.jq";
```

`c.jq`:
```xquery
module namespace c = "c.jq";
```

`query.jq`:
```xquery
import module namespace b = "b.jq";
import module namespace a = "a.jq";
parquet-file("foo.parquet") (: file does not need to exist :)
```

I think I tried removing each of the includes and the warning goes away for any of them.
