### ISSUE TITLE
Document or implement passing integer values into external variables

### ISSUE THREAD

**Issue by ingomueller-net** [RumbleDB/rumble#983]
It should be possible to pass in a value to `$i` in the following query:

```xquery
declare variable $i as integer external := 0; $i
```

However, using the flag `--variable:i 42` results in the following error:

```
⚠️  ️There was an error.

Code: [XPTY0004] (this code can be looked up in the documentation and specifications).

Location information: file:/home/muellein/git/Rumble/external.jq:LINE:1:COLUMN:0:

External variable value (42) does not match the expected type (xs:integer).
```

Is there a trick or is this currently not supported?

**Comment by ghislainfourny** [comment]
Thanks, Ingo. I think for now it always considers the input as a string (except for anyURI that it resolves to a path). I need to add an automatic cast.

**Comment by ghislainfourny** [comment]
@ingomueller-net do you agree if we close this issue?
